-- abbreviations defined by LuaSnip, can be used directly
-- local ls = require("luasnip")
-- local s = ls.snippet
-- local sn = ls.snippet_node
-- local t = ls.text_node
-- local i = ls.insert_node
-- local f = ls.function_node
-- local d = ls.dynamic_node
-- local fmt = require("luasnip.extras.fmt").fmt
-- local fmta = require("luasnip.extras.fmt").fmta
-- local rep = require("luasnip.extras").rep

-- add snippets like followed
-- return {
--   s("trig", t("loaded!!")), -- lua will expand this
-- }
-- a full example
-- return {
--   -- Example: how to set snippet parameters
--   require("luasnip").snippet(
--     { -- Table 1: snippet parameters
--       trig="hi",
--       dscr="An autotriggering snippet that expands 'hi' into 'Hello, world!'",
--       regTrig=false, -- The trigger is not a lua regular expression
--       priority=100, -- default is 1000
--       snippetType="autosnippet"  -- autoexpand the snippet
--     },
--     { -- Table 2: snippet nodes (don't worry about this for now---we'll cover nodes shortly)
--       t("Hello, world!"), -- A single text node
--     }
--     -- Table 3, the advanced snippet options, is left blank.
--   ),
-- }
